#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

#HAS_HDMI_MON="$(bspc query -M --names | grep HDMI)"
#POLYBAR_LOG="$HOME/.polybar.log"
#
#killall -q polybar
#if [ -z "$HAS_HDMI_MON" ]; then
#    $HOME/.local/bin/one-monitor.sh
#    echo '---' | tee -a "$POLYBAR_LOG.eDP-1"
#    MONITOR=eDP-1 polybar top &>> "$POLYBAR_LOG.eDP-1" &
#else
#    $HOME/.local/bin/two-monitors.sh
#    echo '---' | tee -a "$POLYBAR_LOG.eDP-1"
#    echo '---' | tee -a "$POLYBAR_LOG.HDMI-1"
#    MONITOR=eDP-1 polybar top &>> "$POLYBAR_LOG.eDP-1" &
#    MONITOR=HDMI-1 polybar top &>> "$POLYBAR_LOG.HDMI-1" &
#fi

bspc monitor ^1 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor ^2 -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap           1

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
